# Console Filter Configuration
config:

  # Used when the command sender lacks the permission to execute a command
  no-permission-message: '&cYou lack the permission &7consolefilter.reload'
  
  # Used when the reload command was completed.
  config-reloaded-message: '&cConsoleFilter &aConfig reloaded!'
  
  # The amount of days to keep log files (0 or negative value to not delete logs)
  keep-logs: 14
  
  # All messages will be hidden that contain these messages
  filter:
  - 'moved wrongly!,'
  - 'moved too quickly!'
