name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Whitescan
api-version: 1.20
load: STARTUP
main: dev.whitescan.consolefilter.paper.PaperConsoleFilter

commands:
  reloadconsolefilter:
    description: Reload the console filter
    permission: consolefilter.reload
